openapi: 3.0.1
info:
  title: Gateway API
  version: 1.0.0
  description: API Gateway that routes to User, Search, and File APIs.
servers:
   - url: https://localhost:5025
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required: [username, email, password]
      responses:
        '200':
          description: User registered
        '400':
          description: Bad request

  /auth/login:
    post:
      summary: Login and receive JWT
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '200':
          description: JWT token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /auth/profile:
    get:
      summary: Get user profile from JWT token
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
        '401':
          description: Unauthorized

  /search/:
    get:
      summary: Search endpoint (userId injected by gateway)
      tags: [Search]
      security:
        - bearerAuth: []
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Search results
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /files/upload:
    post:
      summary: Upload a file
      tags: [Files]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
        '400':
          description: No file uploaded

  /files/{id}:
    get:
      summary: Get file metadata
      tags: [Files]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File metadata
        '404':
          description: File not found

  /files/delete/{id}:
    delete:
      summary: Delete a file
      tags: [Files]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File deleted
        '404':
          description: File not found

  /files/search:
    get:
      summary: Search files by name
      tags: [Files]
      security:
        - bearerAuth: []
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Files found
        '404':
          description: No files found
